//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk.ViewModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Risk.ViewModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/RiskViewModel;component/Images/Background/gameBg.png.
        /// </summary>
        internal static string gameBg {
            get {
                return ResourceManager.GetString("gameBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/RiskViewModel;component/Images/Planets/planet1.png.
        /// </summary>
        internal static string planet1 {
            get {
                return ResourceManager.GetString("planet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/RiskViewModel;component/Images/Planets/planet2.png.
        /// </summary>
        internal static string planet2 {
            get {
                return ResourceManager.GetString("planet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/RiskViewModel;component/Images/Planets/planet3.png.
        /// </summary>
        internal static string planet3 {
            get {
                return ResourceManager.GetString("planet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/RiskViewModel;component/Images/Planets/planet4.png.
        /// </summary>
        internal static string planet4 {
            get {
                return ResourceManager.GetString("planet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/RiskViewModel;component/Images/Planets/planet5.png.
        /// </summary>
        internal static string planet5 {
            get {
                return ResourceManager.GetString("planet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/RiskViewModel;component/Images/Planets/planet6.png.
        /// </summary>
        internal static string planet6 {
            get {
                return ResourceManager.GetString("planet6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/RiskViewModel;component/Images/Planets/planet7.png.
        /// </summary>
        internal static string planet7 {
            get {
                return ResourceManager.GetString("planet7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/RiskViewModel;component/Images/Planets/planet8.png.
        /// </summary>
        internal static string planet8 {
            get {
                return ResourceManager.GetString("planet8", resourceCulture);
            }
        }
    }
}
